apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # ❗️ Service 타입을 NodePort로 지정합니다.
  type: NodePort
  selector:
    app: frontend
  ports:
    # - protocol: TCP
    #   port: 3000       # Service 자체의 ClusterIP에 대한 포트
    #   targetPort: 3000 # Pod의 컨테이너 포트
    #   nodePort: 30007  # 클러스터의 각 Node(Worker)에 노출될 포트
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30007