apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  # ❗️ Service 타입을 명시하지 않으면 기본값인 ClusterIP로 생성됩니다.
  type: ClusterIP
  selector:
    app: backend # 이 Service가 어떤 Pod를 바라볼지 결정합니다. (app=backend 레이블을 가진 Pod)
  ports:
    - protocol: TCP
      port: 8080 # Service가 노출할 포트
      targetPort: 8080 # Service가 연결할 Pod의 포트
