apiVersion: v1
kind: Secret
metadata:
    name: todo-db-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
    MYSQL_PASSWORD: {{ .Values.database.password }}
