apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-backend
spec:
    replicas: {{ .Values.backend.replicasCount }}
    selector:
        matchLabels:
            app: todo-backend
    template:
        metadata:
            labels:
                app: todo-backend
        spec:
            containers:
                - name: todo-backend
                  image: "{{ .Values.backend.image.repository}}:{{ .Values.backend.image.tag }}"
                  ports:
                      - containerPort: 8080
                  env:
                      - name: DB_HOST
                        value: "todo-service"
                      - name: CORS_ALLOWED_ORIGINS
                        value: {{ .Values.backend.cors_allowed_origins }}
                  envFrom:
                      - configMapRef:
                            name: todo-db-configmap
                      - secretRef:
                            name: todo-db-secret
