apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-list-chart.fullname" . }}-db-configmap
  labels: {{- include "todo-list-chart.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{.Values.database.name}}
  MYSQL_USER: {{.Values.database.user}}